name: annapurna
channels:
- openbabel
- bioconda
- conda-forge
- defaults
- r
dependencies:
- openblas
- future
- matplotlib
- numpy
- pandas=0.18.0
- pip
- readline
- requests=2.2.1=py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.17.1=np110py27_1
- requests-toolbelt
- biopython=1.67
- align_it==1.0.3=3
- seaborn
- urllib3
- wheel
- zlib
- openbabel=2.4.1=py27_1
- progressbar
- python=2.7.14=1
- openjdk=8.0.152
- pip:
  - external_software/h2o-3.9.1.3501/python/h2o-3.9.1.3501-py2.py3-none-any.whl
