name: CI-flake8-python

on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/flake8.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Flake8 action
      uses: suo/flake8-github-action@v1
      with:
        # The name of the check to add annotations to. Generally the same as the job that uses this action
        checkName: testFlake8
