name: install and test
on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/thefirst.yml'
jobs:
  build:
    strategy:
      matrix:
        # os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        # align-it in conda is only for linux 64 bit https://anaconda.org/bioconda/align_it/files
        os: ['ubuntu-16.04', 'ubuntu-latest', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install miniconda and run tests
        shell: bash
        run: |
          echo "---------Fetching miniconda---------"
          wget --quiet https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          echo "---------Setting up---------"
          conda env list
          conda env create -f conda-environment.yml
          conda init bash --dry-run --verbose
          echo "Adding path"
          export XDG_CONFIG_HOME=$HOME/.config
          export PATH="$PATH:$HOME/.dotnet/tools"
          export PATH="$PATH:$HOME/.config/composer/vendor/bin"
          __conda_setup="$('/usr/share/miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
          if [ $? -eq 0 ]; then
              eval "$__conda_setup"
          else
              if [ -f "/usr/share/miniconda/etc/profile.d/conda.sh" ]; then
                  . "/usr/share/miniconda/etc/profile.d/conda.sh"
              else
                  export PATH="/usr/share/miniconda/bin:$PATH"
              fi
          fi
          unset __conda_setup

          echo "---------Activate---------"
          conda activate annapurna
          echo "---------Run tests---------"
          ./annapurna.py --help
          ./annapurna-tests.sh
