name: CI (conda)
on:
  push:
    paths-ignore:
    - 'README.md'
    - '.gitignore'
    - 'models/'
    - 'obrazki/'
    - 'data/'
jobs:
  build:
    strategy:
      matrix:
        # os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        os: ['ubuntu-latest']
        # python-version: [2.7.14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test
        shell: pwsh
        run: |
          wget --quiet https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          conda env list
          ls -la
          conda env create -f conda-environment.yml
          ./annapurna.py --help
          ./annapurna-tests.sh
